spring:
  profiles:
    active: default


invoicing-system:
  database: file
  database.location: db
  database.id.file: id.txt
  database.invoices.file: invoices.txt

logging:
  level:
    pl:
      futurecollars:
        invoicing: INFO
        invoicing.db: DEBUG