server:
  port: 8080

logging:
  level:
    org:
      springframwork:
        boot: INFO
    pl:
      futurecollars:
        invoicing: INFO
        invoicing.db: DEBUG

spring:
  profiles:
    active: file
  flyway:
    enabled: false