/*
 * This Spock specification was generated by the Gradle 'init' task.
 */
package pl.futurecollars.invoicing

import spock.lang.Specification

class InvoicingSystemTest extends Specification {
    def "dummy test to cover main" () {
        setup:
        def app = new InvoicingSystem()

        and:
        app.main()
    }
}
