package pl.futurecollars.invoicing.model;

import io.swagger.annotations.ApiModelProperty;
import java.time.LocalDate;
import java.util.List;
import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.NoArgsConstructor;

@Data
@Builder
@NoArgsConstructor
@AllArgsConstructor
public class Invoice {

  @ApiModelProperty(value = "Invoice id (generated by application)", required = true, example = "1")
  private Integer id;
  @ApiModelProperty(value = "Invoice number (assigned by user)", required = true, example = "2020/03/08/0000001")
  private String number;
  @ApiModelProperty(value = "Date when invoice was created", required = true)
  private LocalDate date;
  @ApiModelProperty(value = "Company which sold the product/service", required = true)
  private Company seller;
  @ApiModelProperty(value = "Company which bought the product/service", required = true)
  private Company buyer;
  @ApiModelProperty(value = "List of products/services", required = true)
  private List<InvoiceEntry> invoiceEntries;

}
